### ISSUE TITLE
tabulate error

### ISSUE THREAD

**Issue by xyfenc** [0xbitx/DEDSEC_NGL_SPAMMER#2]
kapag naka lagay yung from tabulate import tabulate ganto error 

python3 dedsec_ngl.py
Traceback (most recent call last):
  File "/storage/emulated/0/DEDSEC_NGL_SPAMMER/dedsec_ngl.py", line 5, in <module>
    from tabulate import tabulate
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'tabulate'

nung inalis ko yung tabulate ganto naman error 

Traceback (most recent call last):
  File "/storage/emulated/0/DEDSEC_NGL_SPAMMER/dedsec_ngl.py", line 215, in <module>
    menu()
  File "/storage/emulated/0/DEDSEC_NGL_SPAMMER/dedsec_ngl.py", line 178, in menu
    print(tabulate([['TYPE YOUR CRUSH USERNAME']], tablefmt='fancy_grid'))
          ^^^^^^^^
NameError: name 'tabulate' is not defined

**Comment by 0xbitx** [comment]
just install tabulate

**Comment by xyfenc** [comment]
okay but after that i got a new error:(


Traceback (most recent call last):
  File "/storage/emulated/0/DEDSEC_NGL_SPAMMER/dedsec_ngl.py", line 5, in <module>
    from tabulate import tabulate
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/site-packages/tabulate.py", line 7, in <module>
    from collections import namedtuple, Iterable
ImportError: cannot import name 'Iterable' from 'collections' (/data/data/com.termux/files/usr/lib/python3.11/collections/__init__.py)
