### ISSUE TITLE
try it on linux and ubuntu

### ISSUE THREAD

**Issue by Rdeviouz1** [0xbitx/DEDSEC_NGL_SPAMMER#3]
Traceback (most recent call last):
  File "/exec/68747470733a2f2f692e696d6775722e636f6d2f6a76654d44416a2e706e67", line 2, in <module>
  File "<string>", line 3, in <module>
  File "<string>", line 216, in <module>
  File "<string>", line 151, in menu
UnicodeEncodeError: 'ascii' codec can't encode character '\u2800' in position 2112: ordinal not in range(128)

**Comment by 0xbitx** [comment]
web based is available
